AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
